[package]
name = "p3_tokio"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.29"
simple_logger = "5.1.0"
tokio = { version = "1.48.0", features = ["macros", "rt", "rt-multi-thread", "time"] }
